- name: Ensure Homebrew is in the PATH
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: export PATH="/opt/homebrew/bin:$PATH"
    state: present
    insertbefore: EOF

- name: Install brew packages
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - 1password
    - alt-tab
    - bambu-studio
    - bruno
    - coreutils
    - discord
    - epilogue-playback
    - figma
    - firefox
    - ghostty
    - gnupg
    - go
    - google-chrome
    - handbrake
    - jetbrains-toolbox
    - maven
    - nordvpn
    - playback
    - podman-desktop
    - prismlauncher
    - raspberry-pi-imager
    - raycast
    - rectangle
    - sony-ps-remote-play
    - spotify
    - transmit
    - visual-studio-code
    - whatsapp
    - wireguard-go
