- name: Check if ~/.warp exists
  stat:
    path: ~/.warp
  register: warp_stat

- name: Create ~/.warp directory if it doesn't exist
  file:
    path: ~/.warp
    state: directory
    mode: "0755"
  when: not warp_stat.stat.exists

- name: Copy Warp config files to ~/.warp
  copy:
    src: .warp/
    dest: ~/.warp/
    mode: preserve
  when: warp_stat.stat.exists
