- name: Setup Mac for development
  hosts: local
  become: false

  vars:
    ansible_shell_executable: /bin/zsh

  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Enter your sudo password"
      private: yes

    - name: "git_user_name"
      prompt: "Enter your Git user name"
      private: no

    - name: "git_user_email"
      prompt: "Enter your Git email"
      private: no

  roles:
    - sudo
    - homebrew
    - git
    - zsh
    - java
    - nodejs
    - warp
    - workspace
