#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

[[blocks.segments]]
  type = 'text'
  style = 'plain'
  template = '🦊 '

[[blocks.segments]]
  type = 'path'
  style = 'plain'
  background = 'transparent'
  foreground = 'p:orange'
  template = '{{ .Path }} '

  [blocks.segments.properties]
    style = 'full'

[[blocks.segments]]
  type = 'git'
  style = 'plain'
  foreground = 'p:lightgrey'
  background = 'transparent'
  template = '{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <p:orange>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</p:orange>'

  [blocks.segments.properties]
    branch_icon = ''
    commit_icon = '@'
    fetch_status = true

  [properties]
    fetch_status = true
    fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  ## DISABLED: Currently disabled due to bug in warp: https://github.com/warpdotdev/Warp/issues/2304
  # [[blocks.segments]]
  # type = 'text'
  # style = 'plain'
  # foreground = 'p:orange'
  # background = 'transparent'
  # template = '❱'
  ## ENDDISABLED

  [transient_prompt]
    foreground = 'p:orange'
    background = 'transparent'
    template = '❱ '

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:orange'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 1000
      style = 'round'

[palette]
  orange = '#FF5F15'
  lightgrey = '#D3D3D3'